### ISSUE TITLE
Duplicate apt update in common

### ISSUE THREAD

**Issue by pniederlag** [Tuurlijk/TYPO3.Packer#1]
Hi Michiel,

big thx for this awesome initiative!

While digging through the code I spotted some minor glitch. As far as I understand apt update-cache is duplicated in the ansible common role (ansible/roles/common/tasks/main.yml), once guarded by the variable homestead.update_cache and once without any guard.

**Comment by Tuurlijk** [comment]
Thx!

Should be fixed in: https://github.com/Tuurlijk/TYPO3.Packer/commit/c03cc6f1b7ecfdecbb174f41e71e06ce30b449f7

This was to make sure the packages in the just added ppa's were available. I now moved the ppa lines up and removed the second cache update.
