### ISSUE TITLE
Specs for a TYPO3 Coredev Box

### ISSUE THREAD

**Issue by Lefaux** [Tuurlijk/TYPO3.Packer#8]
# Middleware
- nginx
- php5.5 fpm
- php5.6 fpm
- php7 fpm
- elasticsearch nodes (bound to subnet, so multiple boxes in the same LAN don't build a cluster... and don't ask me how I know ;-))
- mailcatcher
- rabbitMQ daemon
- memcached node
- redis node
- graphicsmagick
# Specials
- php versions should be switchable via the url (php7.folder.local.typo3.org)
- php versions should be exposed to the cli for unittests (php7 phpunit.phar --pathToXml)

**Comment by Tuurlijk** [comment]
Building . . .

**Comment by Tuurlijk** [comment]
Update your https://github.com/Tuurlijk/TYPO3.Homestead box and you will have all the things.

One caveat. The phpbrew software uses PECL and that currently does not build the php modules. So no memcached etc. modules for php 7.0.3.

Please test and reopen if stuff needs fixing etc.

**Comment by Tuurlijk** [comment]
Now building with PHP 7.x modules enabled: gd, redis, memcached
